[package]
name = "atcoder1"
version = "0.1.0"
authors = ["web3ten0 <web3ten0@gmail.com>"]
edition = "2018"

[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }
whiteread = "0.5.0"
itertools = "0.10.1"

[[bin]]
name = "main"
path = "src/main.rs"